### ISSUE TITLE
IC2 Classic Support

### ISSUE THREAD

**Issue by Rimusp** [Su5eD/GregTech-Experimental#41]
### Describe the solution you'd like

would be nice to have support for the ic2 classic version from speiger

**Comment by Su5eD** [comment]
Hi, IC2c support for 1.12 GTE is not planned due to its hard dependency on IC2e. Many parts of the codebase use ic2's internals, such as the TEBlock framework, InvSlots, Containers and GUIs. Removing the mandatory dependency would therefore require all of these components to be rewritten.
I initially decided to tightly integrate with IC2e due to IC2c GT being largely covered by [GT Classic](https://www.curseforge.com/minecraft/mc-mods/gregtech-classic) and [GTC Expansion](https://www.curseforge.com/minecraft/mc-mods/gtc-expansion). You can check those mods out, they might have what you're looking for.

#### Future versions
Over time, relying on IC2's closed source internals has proven to be unreliable. To improve the codebase's portability and stability, GTE 1.18.2 and onward will be designed to support other "base" mods as well, such as FTBIC or IC2c. However, I'm a little concerned about IC2c's future considering one of speiger's other mods recently became [paywalled](https://www.reddit.com/r/feedthebeast/comments/wiimsy/the_dev_for_the_chunk_pregen_mod_lost_his_mind/) malware.
