### ISSUE TITLE
Game crash on load

### ISSUE THREAD

**Issue by cliffporter** [Su5eD/GregTech-Experimental#46]
### Describe the bug

The game crashes while loading with ProjectX 2 (and its dependancy, the Silverfish library) installed

### Which side have you encountered the bug on?

Client

### Steps to reproduce

1. Create a 1.12.2 modpack (forge version used: 14.23.5.2846 and 14.23.5.2859, though updating it does not seem to matter)
2. install mods
-CodeChickenLib-1.12.2-3.2.3.357-universal 
 (https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8/files/2755781)
-gregtechmod-0.9.16
-industrialcraft-2-2.8.221-ex112
-ProjectX-1.12.2-2.2.7-universal
 (https://www.curseforge.com/minecraft/mc-mods/projectx-2)
-Silverfish-1.12.2-0.0.19-universal
 (https://www.curseforge.com/minecraft/mc-mods/silverfish)
3. Launch game, crash happens on step 5/7

### Logs

latest.log https://pastebin.com/iDpP5He2

### Additional context

removing either GTEx or ProjectX2 will allow the modpack to load normally.
Silverfish and ProjectX 2 have been abandoned (and PX2 seems to still be incomplete), but are still being used in FTB Ultimate Reloaded.

**Comment by Su5eD** [comment]
Hi, unfortuantely in this case there is nothing that can be done on my side. GTE tries to get the translation key (unlocalized name) of a silverfish item class, which unexpectedly crashed the game.

This is the result of Silverfish not being able to process the item's wildcard metadata value (`32767`). However, GTE doesn't change the metadata of that item, it is already provided to it by the ore dictionary. I assume this issue comes from Silverfish, who registered the item to oredict with a metadata value the mod itself cannot process in the first place.

**Comment by cliffporter** [comment]
Yeah, I was hoping the problem wasn't Silverfish despite the weird interaction, what with it being abandoned and all. 
Thank you for checking though!
