### ISSUE TITLE
[Issue][1.12.2] Compat/Recipe Issue with Nuclear Craft

### ISSUE THREAD

**Issue by accessdenied0** [Su5eD/GregTech-Experimental#48]
### Describe the bug

If I try to load MC with IC2Exp and GT-Exp and Nuclearcraft (newest tested versions), the game crashes with some kind of Recipe Error. Log attached. 

### Which side have you encountered the bug on?

Client

### Steps to reproduce

1. Install MC, newest 1.12.2 Forge
2. Install IC2 Exp.
3. Install GT-Exp.
4. Install Nuclear Craft
5. Crash by loading up.

### Logs

https://github.com/Su5eD/GregTech-Experimental/files/10902191/crash-2023-03-06_20.12.49-client.txt

### Additional context

I am not sure if an different mod can interfere here, too... but the Crash only happens if NC is installed.

I have not yet tried to remove the OD from Mushrooms from the code, to avoid this error, but I am also unsure which Item I need to address specifically, since the Mushrooms-Block in their default have no OD, only the Mushrooms.

[Crash-Log](https://github.com/Su5eD/GregTech-Experimental/files/10902191/crash-2023-03-06_20.12.49-client.txt)

In any case, I do thank you for your work on this mod!

**Comment by Su5eD** [comment]
I've added an error handler for IC2 recipes so that the game doesn't crash should anything go wrong. However, I wasn't able to reproduce the issue myself, so I assume NC isn't the only one in play here with the oredict shenanigans. Either way the fix should be quite universal.
  
Could you try using [this build](https://ci.su5ed.dev/repository/download/GregTechExperimental_BuildBranch/4319:id/gregtechmod-0.9.34.jar)? Just hit `Log in as guest` if prompted to log in and it'll start downloading.

**Comment by accessdenied0** [comment]
I can imagine that some other mod might also cause this... In this pack there are several mods who have to do with OD in regards of Food, in this case it seem to have something to do with the OD of "plant" on Mushroom...
It could be Vanilla Pantry, Pam's Harverstcraft, Vibrant Journey or even a different mod like "Industrial Magic"

I have a few of the mods as tests in this pack to figure out which one I wanna take for my World, but NC and GT-Exp, I would like to keep.

Besides this, the fix works just fine! I am still unsure where it comes from, because I see no recipe of NC interfere with Mushrooms... 

I thank you alot for the fast fix!

**Comment by Su5eD** [comment]
sounds good, pushing the update to CF
