### ISSUE TITLE
Machine Auto Output inconsistent with Overclocker Upgrades

### ISSUE THREAD

**Issue by ThePixelbrain** [Su5eD/GregTech-Experimental#54]
### Describe the bug

The auto output feature seems to be inconsistent and regularly breaking on overclocked GTE machines. I tested it with the Plate Bending Machine and Assembling Machine.

### Which side have you encountered the bug on?

Server

### Steps to reproduce

1. Place down a GTE machine (tested with Plate Bending Machine)
2. Add Overclockers (in my test scenario two Transformer Upgrades and two Overclocker Upgrades)
3. Place an inventory at the auto output side
4. Input items to process

### Additional context

I recorded a small video showing the issue: https://scs.pixelbrain.dev/2p1k1imH.mp4

**Comment by Su5eD** [comment]
I found out this happens because the machine checks for having enough energy before actually ejecting items out of it. The threshold used to be `500 EU`, which I now lowered down to `64 EU` since it will never be higher than the max stack size.

So after processing the input, the machine no longer had enough energy to eject the output and wouldn't receive more until the next tick, getting stuck in a loop. More input energy and a battery upgrade should help with that. Just make sure the machine has sufficient power to keep processing, and the ejection will work smoothly.
